"""Retrieves the reference-document excerpts most relevant to a meeting
transcript, so the summarizer can enrich the summary with authoritative
specifics (vendor names, exact targets, compliance requirements) that
speakers only gesture at generally in conversation.

Two retrieval backends, selected via `method`:
  - "tfidf" (default): pure-Python TF-IDF scoring, no vector DB — same
    approach as phase8-voice-query/src/corpus.py, re-implemented here (not
    shared) since the two phases retrieve over differently-shaped corpora.
  - "faiss": real sentence embeddings + a FAISS index, via the shared
    ../../faiss_retrieval.py — an actual vector database, kept as a second,
    comparable option rather than a replacement, so retrieval quality can
    be compared side by side the same way every other phase in this project
    compares a baseline against an enhancement.
"""
import glob
import math
import os
import re
import sys
from collections import Counter

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
import faiss_retrieval

PHASE_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REFERENCE_DOCS_DIR = os.path.join(PHASE_ROOT, "reference-docs")

STOPWORDS = {
    "the", "a", "an", "and", "or", "of", "to", "in", "on", "for", "is", "are",
    "was", "were", "be", "been", "being", "with", "that", "this", "it", "as",
    "at", "by", "we", "i", "you", "he", "she", "they", "will", "would", "can",
    "could", "so", "but", "if", "not", "do", "does", "did", "have", "has",
    "had", "our", "your", "their", "about", "just", "get", "got",
}
_WORD_RE = re.compile(r"[a-z0-9]+")


def _chunk_markdown(text, source):
    """Splits a '## Heading' doc into one chunk per section, so retrieval
    can point at e.g. just the Payments section of one doc."""
    parts = re.split(r"(?m)^(#{1,6}\s+.+)$", text)
    chunks = []
    if parts[0].strip():
        chunks.append(parts[0].strip())
    for i in range(1, len(parts), 2):
        heading = parts[i].strip()
        body = parts[i + 1].strip() if i + 1 < len(parts) else ""
        combined = f"{heading}\n{body}".strip()
        if combined:
            chunks.append(combined)
    return [{"source": source, "text": c} for c in (chunks or ([text.strip()] if text.strip() else []))]


def build_corpus():
    """Returns one chunk per '##' section across every reference-docs/*.md
    file. Small, fixed set of files — unlike phase8-voice-query's corpus,
    nothing here is optional/missing-tolerant, since these docs ship with
    the phase rather than being generated by an earlier run."""
    chunks = []
    for path in sorted(glob.glob(os.path.join(REFERENCE_DOCS_DIR, "*.md"))):
        source = os.path.splitext(os.path.basename(path))[0]
        with open(path) as f:
            text = f.read()
        for i, chunk in enumerate(_chunk_markdown(text, source)):
            chunks.append({"id": f"{source}#{i}", **chunk})
    return chunks


def _tokenize(text):
    return [t for t in _WORD_RE.findall(text.lower()) if len(t) > 1 and t not in STOPWORDS]


def build_index_tfidf(chunks):
    token_lists = [_tokenize(c["text"]) for c in chunks]
    doc_freq = Counter()
    for tokens in token_lists:
        doc_freq.update(set(tokens))

    n_docs = max(len(chunks), 1)
    idf = {term: math.log((n_docs + 1) / (freq + 1)) + 1 for term, freq in doc_freq.items()}

    indexed = []
    for chunk, tokens in zip(chunks, token_lists):
        indexed.append({**chunk, "_term_counts": Counter(tokens), "_length": len(tokens)})
    return {"chunks": indexed, "idf": idf}


def query_tfidf(index, text, top_k=5):
    """Scores every chunk against `text`'s own terms (the transcript, not a
    short question) — length-normalized TF-IDF, same as phase8-voice-query's
    query(), so long transcripts don't just win by containing more words."""
    q_terms = _tokenize(text)
    scored = []
    for chunk in index["chunks"]:
        score = sum(chunk["_term_counts"].get(t, 0) * index["idf"].get(t, 0) for t in q_terms)
        if score <= 0:
            continue
        norm = math.sqrt(chunk["_length"] + 1)
        scored.append((score / norm, chunk))

    scored.sort(key=lambda pair: pair[0], reverse=True)
    return [
        {"id": c["id"], "source": c["source"], "text": c["text"], "score": s}
        for s, c in scored[:top_k]
    ]


def build_index(chunks, method="tfidf"):
    if method == "faiss":
        return faiss_retrieval.build_index(chunks)
    return build_index_tfidf(chunks)


def query(index, text, top_k=5, method="tfidf"):
    if method == "faiss":
        return faiss_retrieval.query(index, text, top_k=top_k)
    return query_tfidf(index, text, top_k=top_k)


def retrieve_for_transcript(transcript, top_k=5, method="tfidf"):
    index = build_index(build_corpus(), method=method)
    return query(index, transcript, top_k=top_k, method=method)
